apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-dep
  name: test-dep
  namespace: service-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
