FROM golang:1.19 as build_sales-api
ENV CGO_ENABLED 0 
ARG VCS_REF
ARG BUIL_REF

#copying code into container
COPY main.go /service

WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

FROM alpine
ARG BUILD_DATE
ARG BUILD_REF
# go build takes name service from the context of the folder here
COPY --from=build_sales-api /service /service 
WORKDIR /service
CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="William Kennedy <bill@ardanlabs.com>" \
      org.opencontainers.image.source="https://github.com/ardanlabs/service/app/sales-api" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Ardan Labs"